version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: 'ap-south-1'
    SITE_NAME: 'teal.goplinto.com'

phases:
  install:
    commands:
      - echo Installing app dependencies
      - yarn --ignore-engines
  pre_build:
    commands:
      - echo Fetch env file
      - echo aws s3 cp s3://goplinto.config.files/$SITE_NAME/$STAGE/$STORE_ID/.env.$STAGE.local .env.local
      - aws s3 cp s3://goplinto.config.files/$SITE_NAME/$STAGE/$STORE_ID/.env.$STAGE.local .env.local
  build:
    commands:
      - echo Building static site...
      - yarn run build

artifacts:
  # type: zip
  files:
    - '**/*'
  base-directory: build
  discard-paths: no

cache:
  paths:
    - './node_modules/**/*'
